# This workflow will build and (if release) publish Python distributions to PyPI
# For more information see:
#   - https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
#   - https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
#

name: build-publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.3.1
      env:
        CIBW_ARCHS: all
        CIBW_BUILD: cp36-macosx_x86_64
        CIBW_BUILD: cp37-macosx_x86_64
        CIBW_BUILD: cp38-macosx_x86_64
        CIBW_BUILD: cp38-macosx_arm64
        CIBW_BUILD: cp39-macosx_x86_64
        CIBW_BUILD: cp39-macosx_arm64
        CIBW_BUILD: cp36-manylinux_x86_64
        CIBW_BUILD: cp37-manylinux_x86_64
        CIBW_BUILD: cp38-manylinux_x86_64
        CIBW_BUILD: cp39-manylinux_x86_64
        
    - name: Store wheels
      uses: actions/upload-artifact@v2
      with:
        path: ./wheelhouse/*.whl
      
  build-src:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build src
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        python setup.py sdist
    - name: Store src
      uses: actions/upload-artifact@v2
      with:
        path: dist/*.tar.gz

  publish:
    runs-on: ubuntu-latest
    needs:
    - build-wheels
    - build-src
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - name: Download dists
      uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
